/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "PWM_1.h"
#include "MotorPWM_1_BRUN_aliases.h"
#include "MotorPWM_1_BRUN.h"
#include "Forward_ORANGE_aliases.h"
#include "Forward_ORANGE.h"
#include "Clock_1.h"
#include "LED_Red_aliases.h"
#include "LED_Red.h"
#include "LED_PWM.h"
#include "LED_Green_aliases.h"
#include "LED_Green.h"
#include "MotorPWM_2_BLAA_aliases.h"
#include "MotorPWM_2_BLAA.h"
#include "PowerButton_aliases.h"
#include "PowerButton.h"
#include "FollowButton_aliases.h"
#include "FollowButton.h"
#include "UART_1.h"
#include "Backward_GUL_aliases.h"
#include "Backward_GUL.h"
#include "Power_isr.h"
#include "Follow_isr.h"
#include "Clock_4.h"
#include "SPIS.h"
#include "SPIS_PVT.h"
#include "miso_aliases.h"
#include "miso.h"
#include "mosi_aliases.h"
#include "mosi.h"
#include "sclk_aliases.h"
#include "sclk.h"
#include "isr_1.h"
#include "ss_aliases.h"
#include "ss.h"
#include "UART_1_IntClock.h"
#include "SPIS_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

